
# coding: utf-8

# In[2]:

#get_ipython().magic(u'matplotlib inline')
#from IPython.external import mathjax; mathjax.install_mathjax()
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import healpy as hp
import healpy.projector as pro
import pyfits
import pidly
idl = pidly.IDL()


# In[ ]:




# In[3]:

##This file just contains the "setup" for the circular aperture photometry, 
## to be carrie outon HEALPix maps-
## it just definsed the settings and runs the MEP code (test run)
##First, just define the needed variables/settings as you would in IDL (since the syntax is the same), 
##but now you're doing it with the Python terminal
inputlist = 'inputlist_mep_test.list'
maplist  =  'maplist_mep_test.list'
radius = 60.0
rinner = 1.5
router = 2.0
##The following is the general syntax for running and IDL command from Python.. Inside the (), you keep the IDL syntax
#idl('multiepoch_photometry_akari, inputlist, maplist=maplist, radius=radius, rinner=rinner, router=router, /galactic')
##Use the following if you're running a 'named' function...
#idl.multiepoch_photometry_akari(inputlist, maplist=maplist, radius=radius, rinner=rinner, router=router, galactic=True)
##Use the following if you're working with a PROcedure, but not necessarily a named function
idl.pro('multiepoch_photometry_akari',inputlist, maplist=maplist, radius=radius, rinner=rinner, router=router, galactic=True)


# In[4]:

###Now let's play with retrieving values:
#Since the actual photometry is run "within" a the PRO 'multiepoch...pro', 
#we'll have to restore the .SAV file generated by that routine.
#Well, me may not *have* to do it that way, I just haven't yet learned a better way..

idl.pro('restore','multiepoch_photometry_akari_.sav')

###Ok, the actual value-retrieving test...
## This is done with Python.. well, of course it is, that's the point of using pidly!
## You just print a variable like you would any other time, except that you prefix it with 'idl.'


#print idl.ev('fd_all')
fd_all = idl.ev('fd_all')
#print fd_all
#print idl.ev('fd_err_all')
fd_err_all = idl.ev('fd_err_all')
#print fd_err_all


# In[6]:

##We'll be making multiple plots in this one box, so first we set that up:
#Set the "figure number" -
#plt.figure(1)

print 'Comparison of AME with IR Bands: Starting with 9 micron'
R = np.corrcoef(fd_all[0],fd_all[1])
print R

R = np.corrcoef(fd_all[0],fd_all[2])
print R

R = np.corrcoef(fd_all[0],fd_all[3])
print R

R = np.corrcoef(fd_all[0],fd_all[4])
print R

R = np.corrcoef(fd_all[0],fd_all[6])
print R

R = np.corrcoef(fd_all[0],fd_all[7])
print R

R = np.corrcoef(fd_all[0],fd_all[8])
print R

R = np.corrcoef(fd_all[0],fd_all[9])
print R

R = np.corrcoef(fd_all[0],fd_all[10])
print R

R = np.corrcoef(fd_all[0],fd_all[11])
print R


